name = "games"
compatibility_date = "2026-07-03"
main = "workers-site/index.js"
workers_dev = false
route = "games.veyan.ai/*"

[site]
  bucket = "."

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]
